services:
  turtlebot_nav_stage4:
    image: fbe-dockerreg.rwu.de/doz-iki/staehle-vls/amr-tb3:latest
    container_name: turtlebot_nav_stage4
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
      - TURTLEBOT3_MODEL=burger
      - ROS_DOMAIN_ID=36
      - BASH_ENV=/root/.bashrc
      - XAUTHORITY=/root/.Xauthority
    volumes:
      - $IKI_WORKSPACE/26ss_ab-246955/src:/root/iki_ws/src
      - $IKI_WORKSPACE/26ss_ab-246955/install:/root/iki_ws/install
      - $IKI_WORKSPACE/26ss_ab-246955/log:/root/iki_ws/log
      - $IKI_WORKSPACE/26ss_ab-246955/build:/root/iki_ws/build
      - $IKI_WORKSPACE/26ss_ab-246955/maps:/root/iki_ws/maps
      - $IKI_WORKSPACE/my_bash_history:/root/.bash_history
      - $IKI_WORKSPACE/26ss_ab-246955/my_bashrc:/root/.bashrc
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
    working_dir: /root/iki_ws
    network_mode: host  
    ipc: host
    privileged: true
    stdin_open: true
    command:
      - bash
      - -c
      - |
        source /opt/ros/humble/setup.bash &&
        source /usr/share/gazebo/setup.bash &&
        export ROS_DOMAIN_ID=36 &&
        ros2 launch turtlebot3_gazebo turtlebot3_dqn_stage4.launch.py &
        sleep 5 &&
        ros2 launch turtlebot3_navigation2 navigation2.launch.py 'map:=/root/iki_ws/maps/dqn_stage4.yaml' use_sim_time:=True &
        sleep 10 &&
        ros2 run initial_pose_publisher initial_pose_dqn_stage4 &
        tail -f /dev/null