services:
  tiago_container:
    image: fbe-dockerreg.rwu.de/prj-iki-ros2/robots/tiago/tiago_base:sim-ar
    container_name: tiago_container
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=36
      - BASH_ENV=/root/.bashrc
      - XAUTHORITY=/root/.Xauthority
    volumes:
      - $IKI_WORKSPACE/26ss_ab-246955/src:/root/iki_ws/src
      - $IKI_WORKSPACE/26ss_ab-246955/install:/root/iki_ws/install
      - $IKI_WORKSPACE/26ss_ab-246955/log:/root/iki_ws/log
      - $IKI_WORKSPACE/26ss_ab-246955/build:/root/iki_ws/build
      - $IKI_WORKSPACE/26ss_ab-246955/config:/root/iki_ws/config
      - $IKI_WORKSPACE/26ss_ab-246955/maps:/root/iki_ws/maps
      - $IKI_WORKSPACE/26ss_ab-246955/scripts:/root/iki_ws/scripts
      - $IKI_WORKSPACE/my_bash_history:/root/.bash_history
      - $IKI_WORKSPACE/26ss_ab-246955/my_bashrc:/root/.bashrc
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
    working_dir: /root/iki_ws
    network_mode: host  
    ipc: host
    privileged: true
    stdin_open: true
    command:
      - bash
      - -c
      - |
        tail -f /dev/null